---
title: "Bioconductor Notes, September 2025"
date: "2025-09-15"
author:
  - name: Maria Doyle, Bioconductor Community Manager
    affiliation: University of Limerick
  - name: Bioconductor Core Developer Team
    affiliation: Dana-Farber Cancer Institute, Roswell Park Comprehensive Cancer Center, City University of New York, Fred Hutchinson Cancer Research Center, Mass General Brigham
---


# Introduction 

[Bioconductor](https://bioconductor.org) provides
tools for the analysis and comprehension of high-throughput genomic
data.  The project has entered its twenty-first year, with funding
for core development and infrastructure maintenance secured
through 2025 (NIH NHGRI 2U24HG004059).  Additional support is provided
by NIH NCI, Chan-Zuckerberg Initiative, National Science Foundation,
Microsoft, and Amazon. In this news report, we give some updates on 
core team and project activities.
 
# Software

```{r lkdat,results="hide",echo=FALSE}
library(BiocPkgTools)
softli = biocPkgList(version="3.21")
expli = biocPkgList(version="3.21", repo="BioCexp")
worli = biocPkgList(version="3.21", repo="BioCworkflows")
annli = biocPkgList(version="3.21", repo="BioCann")
curR = "4.4"
nsoft = nrow(softli)
nexp = nrow(expli)
nanno = nrow(annli)
nwkfl = nrow(worli)
nbooks = 8
```

Bioconductor [3.21](https://bioconductor.org/news/bioc_3_21_release/), released in April 2025, is now available. It is
compatible with R `r curR` and consists of `r nsoft` software packages, `r nexp`
experiment data packages, `r nanno` up-to-date annotation packages, `r nwkfl`
workflows, and `r nbooks` books. [Books](https://bioconductor.org/books/release/) are
built regularly from source, ensuring full reproducibility; an example is the
community-developed [Orchestrating Single-Cell Analysis with Bioconductor](https://bioconductor.org/books/release/OSCA/).


# Core Team and Infrastructure Updates

Of note: 
<ul>
<li> A pair of machines with NVIDIA GPUs were added to the system.  See
[devel branch build reports](https://bioconductor.org/checkResults/3.22/bioc-gpu-LATEST/) for
more information.
<li> An [HDF5Array vignette](https://bioconductor.org/packages/release/bioc/vignettes/HDF5Array/inst/doc/HDF5Array_performance.html) includes new performance analysis data.
</ul>

NEWS summaries for three contributed packages chosen at random from the 72 new software contributions are:

<!-- set.seed(1234); sample(1:72, size=3) gave indices -->

- **CARDspa**: CARD is a reference-based deconvolution method that estimates cell type composition in spatial transcriptomics based on cell type specific expression information obtained from a reference scRNA-seq data. A key feature of CARD is its ability to accommodate spatial correlation in the cell type composition across tissue locations, enabling accurate and spatially informed cell type deconvolution as well as refined spatial map construction. CARD relies on an efficient optimization algorithm for constrained maximum likelihood estimation and is scalable to spatial transcriptomics with tens of thousands of spatial locations and tens of thousands of genes.

- **G4SNVHunter** G-quadruplexes (G4s) are unique nucleic acid secondary structures predominantly found in guanine-rich regions and have been shown to be involved in various biological regulatory processes. G4SNVHunter is an R package designed to rapidly identify genomic sequences with G4-forming potential and accurately screen user-provided single nucleotide variants (also applicable to single nucleotide polymorphisms) that may destabilize these structures. This enables users to screen key variants for further experimental study, investigating how these variants may influence biological functions, such as gene regulation, by altering G4 formation.

- **jazzPanda** This package contains the function to find marker genes for image-based spatial transcriptomics data. There are functions to create spatial vectors from the cell and transcript coordiantes, which are passed as inputs to find marker genes. Marker genes are detected for every cluster by two approaches. The first approach is by permtuation testing, which is implmented in parallel for finding marker genes for one sample study. The other approach is to build a linear model for every gene. This approach can account for multiple samples and backgound noise.

See the NEWS section in the [release announcement](https://bioconductor.org/news/bioc_3_21_release/) for
a complete account of changes throughout the ecosystem.  



# Community and Impact

## Publications and Preprints

In October 2024, two notable preprints were published by Bioconductor contributors:

- [Eleven quick tips for writing a Bioconductor package](https://osf.io/preprints/osf/wxjky)
Authors: Charlotte Soneson, Lori Shepherd, Marcel Ramos, Kevin Rue-Albrecht, Johannes Rainer, Hervé Pagès, and Vincent J. Carey (Bioconductor Core Team and collaborators).
This preprint provides concise, practical advice for developing high-quality Bioconductor packages.

- [Learning and teaching biological data science in the Bioconductor community](https://arxiv.org/abs/2410.01351)
Authors: Bioconductor Training Committee and others.
This preprint explores the Bioconductor community’s role in advancing biological data science education and training.

## ELIXIR BioHackathon Europe 2024
Bioconductor participated in this collaborative event (November 4–8), held in Barcelona, to advance interoperability and innovation in life sciences. Key contributions included projects focused on EDAM-bio.tools and training infrastructure.

## Training Domain Launch

Bioconductor is developing [training.bioconductor.org](https://training.bioconductor.org/), a centralised website for accessing and organising high-quality Bioconductor training materials. This work is still in progress, with the Training Committee actively discussing ways to restructure existing resources and improve their discoverability. A key focus is supporting community-driven tutorials and emphasising pedagogical quality to better serve learners.

## Bioconductor Carpentry Single-Cell Module

Bioconductor now features an official [single-cell RNA sequencing (scRNA-seq) module](https://carpentries-incubator.github.io/bioc-scrnaseq/) in the Carpentries Incubator. This module, renamed from the Orchestrating Single-Cell Analysis (OSCA) curriculum, provides a structured introduction to scRNA-seq analysis with Bioconductor and is aimed at both learners and educators.



## Galaxy and Bioconductor Community Conference

Announced in September 2024, the first Galaxy and Bioconductor Community Conference (GBCC 2025) is scheduled for June 23-26, 2025, at Cold Spring Harbor Laboratory, New York. The conference aims to showcase the integration of Galaxy and Bioconductor tools, promoting reproducible workflows and community-driven development. For more details, see the [blog post](https://blog.bioconductor.org/posts/2024-09-03-gbcc2025-announcement/).


# Boards and Working Groups Updates

## New Board Members

- The [Community Advisory Board](https://bioconductor.org/about/community-advisory-board/) (CAB) welcomes new members Zahraa Alsafwani, Jasmine Daly, Tobilola Ogunbowale, and Lluis Revilla. We extend our gratitude to outgoing members Daniela Cassol, Estefania Mancini, Jordana Muwanguzi, and Mike Smith for their service.

- The [Technical Advisory Board](https://bioconductor.org/about/technical-advisory-board/) (TAB) welcomes new members Michael Lawrence and Jacques Serizay. Outgoing members Sean Davis and Michael Love are also warmly thanked for their contributions.

## Code of Conduct Committee Elections

In October 2024, Bioconductor sought new members to join its Code of Conduct (CoC) Committee, which plays a vital role in maintaining the integrity and safety of our community. The CoC meets 3–4 times annually to address important issues. Applications are now closed, but you can learn more about the committee and its work on the Code of Conduct page.

If you are interested in becoming involved with any [Bioconductor working group](https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html) please contact the group leader(s).


# Using Bioconductor

Start using
Bioconductor by installing the most recent version of R and evaluating
the commands
```
  if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
  BiocManager::install()
```

Install additional packages and dependencies,
e.g., [SingleCellExperiment](https://bioconductor.org/packages/SingleCellExperiment), with
```
  BiocManager::install("SingleCellExperiment")
```
[Docker](https://bioconductor.org/help/docker/)
images provides a very effective on-ramp for power users to rapidly
obtain access to standardized and scalable computing environments.
Key resources include:


- [bioconductor.org](https://bioconductor.org) to install,
  learn, use, and develop Bioconductor packages.
- A list of [available software](https://bioconductor.org/packages)
  linking to pages describing each package.
- A question-and-answer style
  [user support site](https://support.bioconductor.org) and
  developer-oriented [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).
- A community slack workspace ([sign up](https://slack.bioconductor.org))
   for extended technical discussion.
- The [F1000Research Bioconductor gateway](https://f1000research.com/gateways/bioconductor)
for peer-reviewed Bioconductor workflows as well as conference contributions.
- The [Bioconductor YouTube](https://www.youtube.com/user/bioconductor)
     channel includes recordings of keynote and talks from recent 
     conferences, in addition to 
     video recordings of training courses. 
- Our [package submission](https://github.com/Bioconductor/Contributions)
  repository for open technical review of new packages.

Upcoming and recently completed events are browsable at our
[events page](https://bioconductor.org/help/events/).

The [Technical](https://bioconductor.org/about/technical-advisory-board/)
and and [Community](https://bioconductor.org/about/community-advisory-board/)
Advisory Boards provide guidance to ensure that the project addresses
leading-edge biological problems with advanced technical approaches,
and adopts practices (such as a
project-wide [Code of Conduct](https://bioconductor.org/about/code-of-conduct/))
that encourages all to participate. We look forward to
welcoming you!

We welcome your feedback on these updates and invite you to connect with us through the [Bioconductor Slack](https://slack.bioconductor.org) workspace or by emailing community@bioconductor.org.
