#' Generate a Summary of Commit Logs Using a Language Model
#'
#' This function takes a log of commits and generates a concise summary using a
#' specified language model. The summary is intended to report the progress of
#' several projects to a funding agency.
#'
#' @param commits_log `character()` A character vector containing commit
#'   messages. If multiple commit messages are provided, they will be
#'   concatenated into a single string.
#'
#' @param llm `character(1)` A string specifying the language model to
#'   use. Currently, only "gemini" is supported. Default is "gemini".
#'
#' @returns The function prints the summary generated by the language model.
#'
#' @details The function uses a specified language model to create a summary of
#'   the provided commit messages. The summary is intended to be suitable for
#'   reporting to a funding agency. If the `commits_log` contains multiple
#'   messages, they will be concatenated into a single string before being
#'   passed to the language model.
#'
#' @examplesIf (interactive())
#' commits <- c(
#'     "Initial commit of project alpha",
#'     "Added new feature",
#'     "Fixed bug with new feature"
#' )
#' llm_summary(commits)
#' @export
llm_summary <- function(commits_log, llm = "gemini") {
    if (!identical(length(commits_log), 1L))
        commits_log <- paste(commits_log, collapse = "\n")
    llm <- match.arg(llm)
    chat_model <- switch(
        llm,
        gemini = el_chat_gemini
    )
    chat <- chat_model(
        system_prompt = paste(
            "You are a principal investigator on a large research grant.",
            "Your research team will report to you commit history from ",
            "several projects. Create concise summaries for each project",
            "to report back to the funding agency. Use the compiled commit",
            "histories to create a summary of the work done for each project.",
            "Skip any projects that have no commit messages in their history."
        )
    )

    result <- list(
        summary = chat$chat(commits_log)
    )
    class(result) <- c("llm_summary", class(result))
    result
}

el_chat_gemini <- function(...) {
    API_KEY <- Sys.getenv("GOOGLE_API_KEY")
    stopifnot(nzchar(API_KEY))
    ellmer::chat_gemini(..., api_key = API_KEY)
}

#' @rdname llm_summary
#'
#' @inheritParams base::print
#'
#' @exportS3Method base::print
print.llm_summary <- function(x, ...) {
    summary <- strwrap(x$summary, width = 80L, exdent = 2L)
    cat(
        paste(summary, collapse = "\n")
    )
}
